# MPG Cars

### Introduction:

The following exercise utilizes data from [UC Irvine Machine Learning Repository](https://archive.ics.uci.edu/ml/datasets/Auto+MPG)

### Step 1. Import the necessary libraries

In [1]:
import pandas as pd

### Step 2. Import the first dataset [cars1](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars1.csv) and [cars2](https://raw.githubusercontent.com/guipsamora/pandas_exercises/master/05_Merge/Auto_MPG/cars2.csv).

   ### Step 3. Assign each to a variable called cars1 and cars2

In [ ]:
cars1=pd.read_csv('cars1.csv',sep=',')
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,NaN,NaN,NaN,NaN,NaN
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,NaN,NaN,NaN,NaN,NaN
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,NaN,NaN,NaN,NaN,NaN
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,NaN,NaN,NaN,NaN,NaN
4,17.0,8,302,140,3449,10.5,70,1,ford torino,NaN,NaN,NaN,NaN,NaN

In [4]:
cars2=pd.read_csv('cars2.csv',sep=',')
cars2.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,33.0,4,91,53,1795,17.4,76,3,honda civic
1,20.0,6,225,100,3651,17.7,76,1,dodge aspen se
2,18.0,6,250,78,3574,21.0,76,1,ford granada ghia
3,18.5,6,250,110,3645,16.2,76,1,pontiac ventura sj
4,17.5,6,258,95,3193,17.8,76,1,amc pacer d/l

### Step 4. Oops, it seems our first dataset has some unnamed blank columns, fix cars1

In [5]:
cars1=cars1.loc[:,'mpg':'car']
cars1.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino

### Step 5. What is the number of observations in each dataset?

In [7]:
cars1.shape[0], cars2.shape[0]

(198, 200)

### Step 6. Join cars1 and cars2 into a single DataFrame called cars

In [10]:
cars=pd.concat([cars1,cars2])
cars

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
195,27.0,4,140,86,2790,15.6,82,1,ford mustang gl
196,44.0,4,97,52,2130,24.6,82,2,vw pickup
197,32.0,4,135,84,2295,11.6,82,1,dodge rampage
198,28.0,4,120,79,2625,18.6,82,1,ford ranger
199,31.0,4,119,82,2720,19.4,82,1,chevy s-10

### Step 7. Oops, there is a column missing, called owners. Create a random number Series from 15,000 to 73,000.

In [13]:
import numpy as np
owners=np.random.randint(15000,73000,size=398)
owners

array([28411, 51845, 17224, 50755, 34919, 37998, 60691, 21822, 47765,
       15403, 48761, 71493, 28052, 31243, 49343, 41592, 43296, 43007,
       53144, 46377, 27746, 36731, 37024, 55942, 49280, 37709, 54472,
       19441, 48307, 26019, 72716, 47322, 60154, 36632, 63487, 70102,
       64954, 37494, 15985, 24613, 24626, 67882, 40685, 71926, 16133,
       72764, 26798, 32596, 35292, 47391, 51802, 28350, 31497, 15254,
       43846, 57692, 60655, 70836, 50517, 47670, 59287, 63183, 24508,
       16126, 29813, 19308, 58577, 67275, 55552, 42436, 34834, 46428,
       60633, 66456, 16572, 65092, 39135, 17506, 23754, 41065, 33143,
       57702, 15271, 61843, 16998, 60829, 33501, 72742, 39566, 70218,
       56491, 41437, 50981, 46615, 31957, 36422, 62137, 59586, 52972,
       21319, 61837, 69295, 49845, 16079, 42331, 34157, 37727, 35572,
       70495, 62573, 34540, 44459, 50069, 57670, 57548, 56961, 42504,
       19701, 41094, 23585, 53151, 57993, 71089, 67259, 58543, 47787,
       56210, 17068, 68319, 24765, 46182, 70838, 71715, 21208, 60217,
       36058, 28002, 65409, 26937, 55026, 29017, 38653, 34576, 40670,
       36810, 60567, 40094, 18215, 58617, 22086, 46494, 15670, 42151,
       21485, 53295, 36429, 25522, 64926, 41696, 58629, 33292, 58269,
       34461, 47979, 44987, 28852, 61243, 51715, 48798, 26152, 60957,
       30537, 35021, 19330, 30948, 27315, 40966, 45168, 30305, 57177,
       64155, 43445, 40852, 66195, 35589, 39329, 33724, 59512, 16298,
       57365, 56800, 70278, 61452, 64637, 65112, 46225, 15960, 49641,
       59334, 60535, 45394, 37377, 23216, 27843, 34606, 35507, 66264,
       51606, 55407, 24339, 46171, 62552, 39517, 43500, 27790, 61216,
       45662, 64523, 60468, 44953, 21583, 16982, 33238, 72533, 47925,
       59024, 26877, 38515, 71245, 36963, 41426, 27702, 27764, 45186,
       40854, 46623, 15342, 30740, 27127, 51212, 28607, 22442, 39655,
       15138, 31486, 45567, 63794, 38583, 20145, 47622, 17434, 69775,
       36718, 71744, 64447, 41568, 59730, 39477, 65218, 25909, 46673,
       32985, 35578, 40437, 70361, 34023, 46765, 33885, 47820, 22413,
       18074, 29013, 17647, 39915, 61481, 60157, 46096, 58896, 32277,
       34074, 53278, 62387, 51307, 17004, 43483, 28357, 30352, 40557,
       57982, 23374, 16150, 65078, 21731, 66795, 56266, 32530, 19512,
       37080, 52999, 54216, 71970, 53913, 25783, 64544, 19897, 70146,
       31296, 27966, 60134, 26143, 16108, 50759, 37655, 72627, 35642,
       15396, 32624, 51519, 38616, 72502, 18332, 56262, 54860, 71285,
       60355, 35154, 49925, 15572, 38958, 27735, 61934, 62811, 23222,
       27848, 58924, 20776, 39386, 16319, 56108, 50366, 15080, 58468,
       71407, 61213, 57489, 30042, 58412, 20343, 31313, 60670, 31836,
       45124, 30060, 34135, 41477, 16785, 61988, 22891, 29522, 36952,
       33764, 58502, 23286, 18870, 66557, 53418, 61649, 41176, 35070,
       28371, 54807, 34114, 23310, 44266, 59853, 63977, 27784, 50530,
       61395, 53926, 57577, 41027, 66602, 25129, 30548, 67204, 57311,
       54704, 42886, 62870, 27715, 29283, 18298, 33097, 22136, 31193,
       34876, 37983])

### Step 8. Add the column owners to cars

In [16]:
cars['owners']=owners
cars.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model,origin,car,owners
0,18.0,8,307,130,3504,12.0,70,1,chevrolet chevelle malibu,28411
1,15.0,8,350,165,3693,11.5,70,1,buick skylark 320,51845
2,18.0,8,318,150,3436,11.0,70,1,plymouth satellite,17224
3,16.0,8,304,150,3433,12.0,70,1,amc rebel sst,50755
4,17.0,8,302,140,3449,10.5,70,1,ford torino,34919