# Ex1 - Filtering and Sorting Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [3]:
chipo=pd.read_csv('chipotle.tsv',sep='\t')
chipo
chipo["item_price"] = chipo["item_price"].apply(lambda x: float(x[1:]))

### Step 4. How many products cost more than $10.00?

In [11]:
#chipo['item_price']=chipo['item_price'].str.replace("$","").astype(float)
products_more_than=chipo[chipo['item_price']>10.00].value_counts()
len(products_more_than)

1116

### Step 5. What is the price of each item? 
###### print a data frame with only three columns item_name choice_description and product_price

In [24]:
price_for_each=chipo[['item_name','choice_description','item_price']].drop_duplicates()
price_for_each
#drop_duplicates() -> Arata-mi TABELUL curatat
price_unique=chipo[['item_name','choice_description','item_price']].nunique()
price_for_each
#nunique-> imi da doar numarul lor cate is

,item_name,choice_description,item_price
0,Chips and Fresh Tomato Salsa,NaN,2.39
1,Izze,[Clementine],3.39
2,Nantucket Nectar,[Apple],3.39
3,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
4,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",16.98
...,...,...,...
4602,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4607,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4610,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25

### Step 6. Sort by the name of the item

In [28]:
chipo.sort_values('item_name').reset_index()

,index,order_id,quantity,item_name,choice_description,item_price
0,3389,1360,2,6 Pack Soft Drink,[Diet Coke],12.98
1,341,148,1,6 Pack Soft Drink,[Diet Coke],6.49
2,1849,749,1,6 Pack Soft Drink,[Coke],6.49
3,1860,754,1,6 Pack Soft Drink,[Diet Coke],6.49
4,2713,1076,1,6 Pack Soft Drink,[Coke],6.49
...,...,...,...,...,...,...
4617,2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
4618,781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",8.75
4619,2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",8.49
4620,1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
4621,1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",8.49

### Step 7. What was the quantity of the most expensive item ordered?

In [35]:
index_max=chipo["item_price"].idxmax()

chipo['quantity'].iloc[index_max]

np.int64(15)

In [46]:
max_item_price_row=chipo[chipo['item_price']==chipo['item_price'].max()].reset_index()
max_item_price_row['quantity']

0    15
Name: quantity, dtype: int64

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [ ]:
count_item_name=chipo['item_name'].value_counts()
count_item_name['Veggie Salad Bowl']

np.int64(18)

In [63]:
chipo[chipo['item_name']=='Veggie Salad Bowl'].shape[0]

18

### Step 9. How many times did someone order more than one Canned Soda?

In [18]:
soda_ordered=chipo[chipo['item_name'] == 'Canned Soda'].value_counts().reset_index()
nr_soda=soda_ordered[soda_ordered['quantity']>1].value_counts()
len(nr_soda)

20

In [24]:
chipo[ ( chipo["item_name"]=="Canned Soda" ) & ( chipo["quantity"]>1 )].shape[0]

20