# Ex2 - Getting and Knowing your Data

This time we are going to pull data directly from the internet.
Special thanks to: https://github.com/justmarkham for sharing the dataset and materials.

### Step 1. Import the necessary libraries

In [2]:
import pandas as pd

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv).

### Step 3. Assign it to a variable called chipo.

In [64]:
chipo=pd.read_csv('chipotle.tsv',sep='\t')
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

### Step 4. See the first 10 entries

In [6]:
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

### Step 5. What is the number of observations in the dataset?

In [12]:
# Solution 1
chipo.shape 
#rows and columns

(4622, 5)

In [11]:
# Solution 2

len(chipo)

4622

### Step 6. What is the number of columns in the dataset?

In [20]:
chipo.shape[1]

5

### Step 7. Print the name of all the columns.

In [23]:
chipo.columns

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='str')

### Step 8. How is the dataset indexed?

In [24]:
chipo.index

RangeIndex(start=0, stop=4622, step=1)

### Step 9. Which was the most-ordered item?

In [ ]:
# ca sa adunam numerele trb sa le scoatem $ si sa le facem flaot 
# apoi trb comentat ca nu poate sa faca replace de la float la str
#chipo['item_price']=chipo['item_price'].str.replace("$","").astype(float)
sum_items=chipo.groupby('item_name')['item_price'].sum().reset_index()
#daca eu fac asa imi va merge pe priam coloana cu nume si va auta alfabetic acre ste primul si apoi pe a 2 a coloaan si v a vedea suma maxima si le va unii
#sum_items.max()

# a 2 a varianta 
rezultat_2=sum_items.sort_values('item_price',ascending=False).head(1)
rezultat_2
#varianta 1
index_max = sum_items['item_price'].idxmax()
rezultat_rapid = sum_items.iloc[index_max]
rezultat_rapid

#vaianta 3 
cel_mai_comandat=chipo['item_name'].value_counts().idxmax()
cel_mai_comandat

NameError: name 'chipo' is not defined

### Step 10. For the most-ordered item, how many items were ordered?

In [120]:
cantitate = chipo.groupby("item_name")["quantity"].sum().idxmax()
total_cantitate = chipo.groupby("item_name")["quantity"].sum().max()
print(f"Produsul: {cantitate}, Cantitate: {total_cantitate}")


quantity_ceva=chipo.groupby('item_name')['quantity'].sum()
quantity_ceva.sort_values(ascending=False).head(1)

Produsul: Chicken Bowl, Cantitate: 761

item_name
Chicken Bowl    761
Name: quantity, dtype: int64

### Step 11. What was the most ordered item in the choice_description column?

In [121]:
print(chipo["choice_description"].value_counts().idxmax())

[Diet Coke]

### Step 12. How many items were orderd in total?

In [123]:
chipo['quantity'].sum()
print(chipo["quantity"].sum())

4972

### Step 13. Turn the item price into a float

#### Step 13.a. Check the item price type

In [127]:
chipo['item_price'].dtype

dtype('float64')

#### Step 13.b. Create a lambda function and change the type of item price

In [129]:
chipo["item_price"] = chipo["item_price"].apply(lambda x: float(x[1:]))
chipo['item_price'] = chipo['item_price'].apply(lambda x: float(x[1:]) )

TypeError: 'float' object is not subscriptable

#### Step 13.c. Check the item price type

In [128]:
chipo['item_price'].dtype

dtype('float64')

### Step 14. How much was the revenue for the period in the dataset?

In [183]:
chipo['revenue']=chipo['quantity']*chipo['item_price']
chipo['revenue'].sum()
venit_per_produs = chipo.groupby('item_name')['revenue'].sum()

# O sortam ca sa vedem topul
venit_per_produs = venit_per_produs.sort_values(ascending=False)

print(venit_per_produs)
total_revenue = chipo["revenue"].sum()

item_name
Chicken Bowl                             8044.63
Chicken Burrito                          6387.06
Steak Burrito                            4236.13
Steak Bowl                               2479.81
Chips and Guacamole                      2475.62
Chicken Salad Bowl                       1506.25
Chicken Soft Tacos                       1199.01
Chips and Fresh Tomato Salsa             1033.96
Veggie Burrito                           1002.27
Veggie Bowl                               901.95
Barbacoa Burrito                          894.75
Carnitas Bowl                             830.71
Barbacoa Bowl                             672.36
Bottled Water                             649.18
Carnitas Burrito                          616.33
Canned Soft Drink                         603.75
Chips                                     580.34
Steak Soft Tacos                          554.55
Chicken Crispy Tacos                      524.11
Steak Salad Bowl                          391.15
Carnitas Soft Tacos                       375.94
Steak Crispy Tacos                        375.32
6 Pack Soft Drink                         369.93
Side of Chips                             290.68
Barbacoa Soft Tacos                       250.46
Canned Soda                               191.84
Veggie Salad Bowl                         182.50
Chips and Tomatillo Red Chili Salsa       159.30
Chips and Tomatillo Green Chili Salsa     144.55
Barbacoa Crispy Tacos                     138.71
Nantucket Nectar                          111.87
Barbacoa Salad Bowl                       106.40
Carnitas Crispy Tacos                      95.94
Chips and Tomatillo-Red Chili Salsa        93.21
Veggie Soft Tacos                          90.94
Chips and Tomatillo-Green Chili Salsa      88.43
Chicken Salad                              81.09
Bowl                                       74.00
Chips and Roasted Chili Corn Salsa         73.75
Izze                                       67.80
Carnitas Salad Bowl                        66.34
Veggie Salad                               50.94
Burrito                                    44.40
Chips and Roasted Chili-Corn Salsa         43.02
Steak Salad                                35.66
Crispy Tacos                               14.80
Salad                                      14.80
Carnitas Salad                              8.99
Veggie Crispy Tacos                         8.49
Chips and Mild Fresh Tomato Salsa           3.00
Name: revenue, dtype: float64

In [ ]:
# Extragi direct numele celui care are valoarea maxima
nume_produs = venit_per_produs.idxmax()

# Extragi direct valoarea maxima matematica
bani_incasati = venit_per_produs.max()

print("Cel mai banos produs este:", nume_produs)
print("Venitul generat:", bani_incasati)

# sau folosesc reset_index ca sa l fac dataframe si apoi accesez cu iloc[0,0]
tabel_venit=venit_per_produs.reset_index()
tabel_venit.iloc[0,1]

### Step 15. How many orders were made in the period?

In [178]:
chipo['order_id'].nunique()

1834

### Step 16. What is the average revenue amount per order?

In [ ]:
# Solution 1
revenue_per_order = chipo.groupby("order_id")["revenue"].sum()
print("Solutia 1:", f"${revenue_per_order.mean():.2f}")

Solutia 1: $21.39
Solutia 2: $21.39

In [ ]:
# Solution 2

print("Solutia 2:", f"${total_revenue / chipo['order_id'].nunique():.2f}")

### Step 17. How many different items are sold?

In [ ]:
print(chipo["item_name"].nunique())

50